FROM php:8.1-apache

# PostgreSQL ke liye required tools install karo
RUN apt-get update && apt-get install -y \
    libpq-dev \
    && docker-php-ext-install pdo pdo_pgsql

WORKDIR /var/www/html

COPY . .
